name: Sync Fork

on:
  push:
    branches:
      - main  # Altere para o nome da branch que você deseja monitorar

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger sync workflow on fork
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/biassumcao/BookManagerAngularApp/actions/workflows/sync.yml/dispatches \
          -d '{"ref":"main"}'
